spring:
  data:
    redis:
      url: redis://127.0.0.1:6379
  main:
    allow-bean-definition-overriding: 'true'
    web-application-type: 'reactive'
  cloud:
    loadbalancer:
      ribbon:
        enabled: 'false'
  data:
    redis:
      url: redis://127.0.0.1:6379
  application:
    name: feed-reactive
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
api:
  cached: 'false'
  cache:
    local: 'false'

server:
  port: 8090

gateaway:
  api:
    address: http://localhost:8080/

api:
  cached: 'false'
  cache:
    local: 'false'