spring:
  main:
    allow-bean-definition-overriding: 'true'
    web-application-type: 'reactive'
  cloud:
    loadbalancer:
      ribbon:
        enabled: 'false'
    function:
      definition: retrieveFeedPosts;retrievePostsSongs;buildFeed;printFeedPosts;printErrorsFeed
    stream:
      bindings:
        retrieveFeedPosts-in-0:
          destination: getfeed
        retrieveFeedPosts-out-0:
          destination: getposts
        retrievePostsSongs-in-0:
          destination: posts
        retrievePostsSongs-out-0:
          destination: buildfeed
        retrievePostsSongs-out-1:
          destination: getsongs
        buildFeed-in-0:
          destination: buildfeed
        buildFeed-in-1:
          destination: songs
        buildFeed-out-0:
          destination: feed
        printFeedPosts-in-0:
          destination: feed
        printErrorsFeed-in-0:
          destination: errorsfeed
      # kafka:
      #   binder:
      #     brokers: localhost:9092
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 5s

  data:
    redis:
      url: redis://127.0.0.1:6379
  application:
    name: event-driven-feed
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8091

api:
  cached: 'false'
  cache:
    local: 'false'