version: '3.9'
services:
  rabbitmq:
    container_name: rabbit_songday
    image: rabbitmq:3.11.10-management
    hostname: rabbit_songday
    networks:
      - songday-network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      TZ: "America/Fortaleza"
    ports:
      - 5672:5672
      - 15672:15672
      - 15675:15675
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 10

  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    networks:
      - songday-network
    ports:
      - '2181:2181'
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    networks:
      - songday-network
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - songday-network
    ports:
      - '8090:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER_CONNECT=zookeeper:2181

networks:
  songday-network: